services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: unless-stopped
    volumes:
      - /app/node_modules
      - /app/.next
  jobs:
    build: .
    command: ["node", "--import", "tsx", "src/jobs/index.ts"]
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
