import type { Metadata } from "next";
import "./globals.css";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`min-h-screen flex flex-col ${montserrat.className}`}>
        <nav className="w-full py-[14px] bg-white flex justify-center items-center shadow-[0 1px 0 0 #dadada]">
          <h1 className="antialiased text-[18px] font-bold text-green-teal align-center">
            Star Wars Search
          </h1>
        </nav>
        <main className="flex flex-row flex-1 p-[30px] justify-center bg-[#ededed] text-black">
          {children}
        </main>
      </body>
    </html>
  );
}
