import type { Metadata } from "next";
import "./globals.css";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <nav className="w-full py-[7px] bg-white flex justify-center shadow-md">
          <h1 className={`${montserrat.variable} antialiased text-[9px] font-bold text-green-teal`}>Star Wars Search</h1>
        </nav>
        <main className="flex flex=col p-[15px] justify-center bg-[#ededed]">
          {children}
        </main>
      </body>
    </html>
  );
}
